### ISSUE TITLE
微信机器人报错

### ISSUE THREAD

**Issue by xinxijishuwyq** [FengLi666/sports#3]
Traceback (most recent call last):
  File "wechat_bot.py", line 23, in <module>
    from mysports.run import run
ModuleNotFoundError: No module named 'mysports'

**Comment by astronaut0131** [comment]
```
git clone https://github.com/FengLi666/sports.git
cd sports
pip3 install -r requirement.txt
python3 ./wechat_bot/wechat_bot.py
```
是这样操作后报出上述错误的吗？

**Comment by xinxijishuwyq** [comment]
> ```
> git clone https://github.com/FengLi666/sports.git
> cd sports
> pip3 install -r requirement.txt
> python3 ./wechat_bot/wechat_bot.py
> ```
> 是这样操作后报出上述错误的吗？

解决了，谢谢

**Comment by xinxijishuwyq** [comment]
> > ```
> > git clone https://github.com/FengLi666/sports.git
> > cd sports
> > pip3 install -r requirement.txt
> > python3 ./wechat_bot/wechat_bot.py
> > ```
> > 是这样操作后报出上述错误的吗？
> 
> 解决了，谢谢

把mysports文件夹复制到wechat_bot里面即可
