### ISSUE TITLE
检查点乱飞导致路径往往几十公里

### ISSUE THREAD

**Issue by 598597535** [FengLi666/sports#6]
刚用，一看60公里，然后app看了发现检查点都不知道在哪，有啥解决办法吗

**Comment by astronaut0131** [comment]
怎么复现

**Comment by 598597535** [comment]
[图片]

**Comment by 598597535** [comment]
是否可以通过修改\sports-master\path_plan的plan.py中的地址来精确定位，之后用pyinstaller来打包成EXE？（小白问题）

**Comment by astronaut0131** [comment]
就是这么做的

**Comment by 598597535** [comment]
> 就是这么做的

PyInstaller打包哪个.py啊，这个不太懂

**Comment by FengLi666** [comment]
这里是百度地图api的一个参数，当时没考虑到，没试过非上海会有什么影响，你可以尝试改一下
https://github.com/FengLi666/sports/blob/f6a784ec1166de469b2c3b8d728f10297bc3f50a/path_plan/plan.py#L31

打包 mysports/run.py

**Comment by 598597535** [comment]
> 这里是百度地图api的一个参数，当时没考虑到，没试过非上海会有什么影响，你可以尝试改一下
> [sports/path_plan/plan.py](https://github.com/FengLi666/sports/blob/f6a784ec1166de469b2c3b8d728f10297bc3f50a/path_plan/plan.py#L31)
> Line 31 in [f6a784e](/FengLi666/sports/commit/f6a784ec1166de469b2c3b8d728f10297bc3f50a)
>  def get_route(startp: str, endp: str, region='上海'): 
> 打包 mysports/run.py

上面就是说这个，也只有上海的高校用这玩意，就是定位不精确的时候会把检查点弄的很远。
我是想改这个不过不知道咋打包成.exe，丢人了

**Comment by FengLi666** [comment]
> > 这里是百度地图api的一个参数，当时没考虑到，没试过非上海会有什么影响，你可以尝试改一下
> > [sports/path_plan/plan.py](https://github.com/FengLi666/sports/blob/f6a784ec1166de469b2c3b8d728f10297bc3f50a/path_plan/plan.py#L31)
> > Line 31 in [f6a784e](/FengLi666/sports/commit/f6a784ec1166de469b2c3b8d728f10297bc3f50a)
> > def get_route(startp: str, endp: str, region='上海'):
> > 打包 mysports/run.py
> 
> 上面就是说这个，也只有上海的高校用这玩意，就是定位不精确的时候会把检查点弄的很远。
> 我是想改这个不过不知道咋打包成.exe，丢人了

用 pyinstaller 打包  sports/mysports/run.py

**Comment by 598597535** [comment]
pyinstaller E:\BaiduNetdiskDownload\sports-master\mysports\run.py
这样出来的exe还是会闪退
pyinstaller -F E:\BaiduNetdiskDownload\sports-master\mysports\run.py
打包成单个文件也是闪退
pyinstaller -F -p E:\BaiduNetdiskDownload\sports-master\mysports;E:\BaiduNetdiskDownload\sports-master\path_plan;E:\BaiduNetdiskDownload\sports-master\dolike;E:\BaiduNetdiskDownload\sports-master\mysports\run.py
还看了百度添加什么库，这样就显示参数不足
比较头大

**Comment by 598597535** [comment]
> > > 这里是百度地图api的一个参数，当时没考虑到，没试过非上海会有什么影响，你可以尝试改一下
> > > [sports/path_plan/plan.py](https://github.com/FengLi666/sports/blob/f6a784ec1166de469b2c3b8d728f10297bc3f50a/path_plan/plan.py#L31)
> > > Line 31 in [f6a784e](/FengLi666/sports/commit/f6a784ec1166de469b2c3b8d728f10297bc3f50a)
> > > def get_route(startp: str, endp: str, region='上海'):
> > > 打包 mysports/run.py
> > 
> > 
> > 上面就是说这个，也只有上海的高校用这玩意，就是定位不精确的时候会把检查点弄的很远。
> > 我是想改这个不过不知道咋打包成.exe，丢人了
> 
> 用 pyinstaller 打包 sports/mysports/run.py

好像产生了错误缺少了什么：sports-master\mysports\build\run\warn-run.txt中的
missing module named readline - imported by cmd (delayed, conditional, optional), pdb (delayed, optional)
missing module named org - imported by pickle (optional)
missing module named fcntl - imported by tempfile (optional), subprocess (conditional)
missing module named riscosenviron - imported by os (conditional, optional)
missing module named riscospath - imported by os (conditional)
missing module named riscos - imported by os (conditional, optional)
missing module named ce - imported by os (conditional, optional)
missing module named _emx_link - imported by os (conditional)
missing module named os2 - imported by os (conditional, optional)
missing module named pwd - imported by posixpath (delayed, conditional)
missing module named posix - imported by os (conditional, optional)
missing module named resource - imported by posix (top-level)
missing module named 'org.python' - imported by copy (optional)
invalid module named mysports.no_free_run - imported by E:\BaiduNetdiskDownload\sports-master\mysports\run.py (top-level)
missing module named requests - imported by mysports.login (top-level)
missing module named netbios - imported by uuid (delayed)
missing module named win32wnet - imported by uuid (delayed)

**Comment by 598597535** [comment]
> > > 这里是百度地图api的一个参数，当时没考虑到，没试过非上海会有什么影响，你可以尝试改一下
> > > [sports/path_plan/plan.py](https://github.com/FengLi666/sports/blob/f6a784ec1166de469b2c3b8d728f10297bc3f50a/path_plan/plan.py#L31)
> > > Line 31 in [f6a784e](/FengLi666/sports/commit/f6a784ec1166de469b2c3b8d728f10297bc3f50a)
> > > def get_route(startp: str, endp: str, region='上海'):
> > > 打包 mysports/run.py
> > 
> > 
> > 上面就是说这个，也只有上海的高校用这玩意，就是定位不精确的时候会把检查点弄的很远。
> > 我是想改这个不过不知道咋打包成.exe，丢人了
> 
> 用 pyinstaller 打包 sports/mysports/run.py

修改了打包成功后也还是几十公里，我是东华大学的，看来没救了

**Comment by astronaut0131** [comment]
晚上我注册个东华的账号试试（

**Comment by 598597535** [comment]
有没有可能加一个判定，超过4公里就重新锻炼呢

**Comment by astronaut0131** [comment]
我试了试东华松江校区会跑到普陀校区 猜想app根本还没支持松江校区？你自己跑行吗

**Comment by astronaut0131** [comment]
试了试延安路校区正常

**Comment by 598597535** [comment]
> 我试了试东华松江校区会跑到普陀校区 猜想app根本还没支持松江校区？你自己跑行吗

哦哦哦，原来这样，没办法的话我就自己上了，麻烦了

**Comment by astronaut0131** [comment]
可以做个支持自定义输入坐标点的 不麻烦 有空了就给做下

**Comment by 598597535** [comment]
> 可以做个支持自定义输入坐标点的 不麻烦 有空了就给做下

刚刚想跑一圈发现都能在本校的范围内啊

**Comment by 598597535** [comment]
这东西在15号有过一次更新

**Comment by astronaut0131** [comment]
晚点仔细看下怎么回事

**Comment by astronaut0131** [comment]
找到原因了 
原因还是app问题，app返回红点绿点的时候会把松江校区和延安路校区的点混在一起返回 
一个临时的解决办法是

https://github.com/FengLi666/sports/blob/f6a784ec1166de469b2c3b8d728f10297bc3f50a/mysports/no_free_run.py#L18 
和https://github.com/FengLi666/sports/blob/f6a784ec1166de469b2c3b8d728f10297bc3f50a/mysports/no_free_run.py#L19
改成
`
    no_free_data['bNode'] = [item for item in resj['ibeacon'] if float(item['position']['longitude']) < 121.3]
    `
和
`no_free_data['tNode'] = [item for item in resj['gpsinfo'] if float(item['longitude']) < 121.3]`
亲测可用

**Comment by astronaut0131** [comment]
最新提交已对所有有两个校区的学校做了特殊处理 have a try
