### ISSUE TITLE
微信机器人显示二维码错乱

### ISSUE THREAD

**Issue by gadfly3173** [FengLi666/sports#7]
![tim 20181122013435](https://user-images.githubusercontent.com/28685179/48858608-cce38280-edf6-11e8-92c6-5c74adeea01d.png)

**Comment by astronaut0131** [comment]
https://github.com/FengLi666/sports/blob/2290558a0a76fa4cb1f3ea3a8e3598e9960104aa/wechat_bot/wechat_bot.py#L12
可以试试去掉consult_qr

**Comment by gadfly3173** [comment]
解决了，win下需要设为1，linux下才是2
